---
- hosts: all
  become: yes
  tasks:

   - name: Wait for previous ansible run to complete
     shell: while ps -ef | grep -i k8-on-lza-all.yaml | grep -v 'grep' ; do sleep 10; done;

   - name: Wait for /var/lib/dpkg/lock-frontend to be released 
     shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;

   - name: Wait for /var/lib/apt/lists/lock to be released 
     shell: while lsof /var/lib/apt/lists/lock ; do sleep 10; done;

   - name: ensures dir exists
     file: 
       path: "/run/flannel"
       state: directory
     register: lsresult
     until: "lsresult is not failed"
     delay: 10
     retries: 12

   - name: Creating a file with content
     copy:
       dest: "/run/flannel/subnet.env"
       content: |
         FLANNEL_NETWORK=10.244.0.0/16
         FLANNEL_SUBNET=10.244.0.1/24
         FLANNEL_MTU=1450
         FLANNEL_IPMASQ=true
     register: lsresult
     until: "lsresult is not failed"
     delay: 10
     retries: 12

   - name: Download join_command from S3
     amazon.aws.s3_object:
       bucket: "{{ bucket }}"
       object: join_node_command
       dest: /tmp/join_node_command.sh
       mode: get
     register: lsresult
     until: "lsresult is not failed"
     delay: 10
     retries: 12

   - name: Change file ownership, group and permissions
     ansible.builtin.file:
       path: /tmp/join_node_command.sh
       mode: '0777'
     register: lsresult
     until: "lsresult is not failed"
     delay: 10
     retries: 12

   - name: Add cri socket to kubelet
     replace:
       path: /tmp/join_node_command.sh
       regexp: "--token"
       replace: "--cri-socket='/run/cri-dockerd.sock' --token"
     register: lsresult
     until: "lsresult is not failed"
     delay: 10
     retries: 12

   - name: Join the worker node to cluster
     command: sh /tmp/join_node_command.sh
     register: lsresult
     until: "lsresult is not failed"
     delay: 10
     retries: 12