---
- hosts: all
  become: yes
  tasks:
  #  - name: Sleep for 15 minutes and continue with play
  #    ansible.builtin.wait_for:
  #      timeout: 900

   - name: Wait for previous ansible run to complete
     shell: while ps -ef | grep -i k8-on-lza-all.yaml | grep -v 'grep' ; do sleep 10; done;

   - name: Wait for /var/lib/dpkg/lock-frontend to be released 
     shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;

   - name: Kubectl Install
     apt:
       name: kubectl
       state: present
       force: yes
     delay: 10
     retries: 12

   - name: Download join_command from S3
     amazon.aws.s3_object:
       bucket: "{{ bucket }}"
       object: join_command
       dest: /tmp/join_command.sh
       mode: get
     delay: 10
     retries: 12

   - name: Change file ownership, group and permissions
     ansible.builtin.file:
       path: /tmp/join_command.sh
       mode: '0777'
     delay: 10
     retries: 12

   - name: Add cri socket to kubelet
     replace:
      path: /tmp/join_command.sh
      regexp: "--token"
      replace: "--cri-socket='/run/cri-dockerd.sock' --token"
     delay: 10
     retries: 12

   - name: Join the master node to cluster
     command: sh /tmp/join_command.sh
     delay: 10
     retries: 12

   - name: Sleep for 20 seconds
     wait_for:
      timeout: 20
     delay: 10
     retries: 12

   - name: Create .kube directory
     become: yes
     become_user: ubuntu
     file:
       path: $HOME/.kube
       state: directory
       mode: 0755
     delay: 10
     retries: 12

   - name: Check admin.conf file exists.
     stat:
       path: /etc/kubernetes/admin.conf
     register: k8s_conf
     delay: 10
     retries: 12

   - name: Copy admin.conf to user's kube config
     copy:
       src: /etc/kubernetes/admin.conf
       dest: /home/ubuntu/.kube/config
       remote_src: yes
       owner: ubuntu
     when: k8s_conf.stat.exists
     delay: 10
     retries: 12