---
- hosts: all
  become: yes
  tasks:
   - name: Docker Installation
     apt:
       name: docker.io
       state: present
       update_cache: true

   - name: Install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present

   - name: Add Kubernetes apt-key for APT repository
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: Add Kubernetes APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   - name: Kubelet Install
     apt:
       name: kubelet
       state: present
       update_cache: true

   - name: Kubeadm Install
     apt:
       name: kubeadm
       state: present
       update_cache: true

## Install cri-dockerd as Docker Engine shim for Kubernetes
      
   - name: Get cri-dockerd latest Version number
     uri:
      url: https://api.github.com/repos/Mirantis/cri-dockerd/releases/latest
      timeout: 10
     register: cri_dockerd_latest

   - debug:
      var: cri_dockerd_latest.json.tag_name

   - name: Download cri-dockerd
     get_url:
        url: https://github.com/Mirantis/cri-dockerd/releases/download/{{ cri_dockerd_latest.json.tag_name }}/cri-dockerd-{{ cri_dockerd_latest.json.tag_name | replace('v','') }}.amd64.tgz
        dest: /home/ubuntu

   - name: Extract cri_dockerd
     ansible.builtin.unarchive:
        src: /home/ubuntu/cri-dockerd-{{ cri_dockerd_latest.json.tag_name | replace('v','') }}.amd64.tgz
        dest: /usr/local/bin/
        extra_opts: [--strip-components=1]
        remote_src: yes

   - name: systemd units for cri-dockerd - cri-docker.service
     get_url:
        url: https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.service
        dest: /etc/systemd/system/

   - name: systemd units for cri-dockerd - cri-docker.socket
     get_url:
        url: https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.socket
        dest: /etc/systemd/system/

   - name: Configure systemd for cri-dockerd
     replace: 
        path: /etc/systemd/system/cri-docker.service
        regexp: "/usr/bin/cri-dockerd"
        replace: "/usr/local/bin/cri-dockerd"

   - name: Just force systemd to reread configs (2.4 and above)
     ansible.builtin.systemd:
        daemon_reload: yes

   - name: Start and Enable the cri-dockerd service - cri-docker.service
     ansible.builtin.systemd:
      name: cri-docker.service
      state: started
      enabled: yes

   - name: Start and Enable the cri-dockerd service - cri-docker.socket
     ansible.builtin.systemd:
      name: cri-docker.socket
      state: started
      enabled: yes

   - name: Install Ansible AWS tools
     shell: ansible-galaxy collection install amazon.aws
     register: result

   - name: Install boto3
     shell: pip3 install boto3
     register: result

   - name: Install lsof
     apt:
       name: lsof
       state: present
       update_cache: true